# Generated by Django 4.0.4 on 2022-04-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Morador',
                'verbose_name_plural': 'Moradores',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.morador', verbose_name='Morador')),
                ('familia', models.TextField(max_length=200, verbose_name='Dependentes')),
                ('tempo', models.TimeField(verbose_name='Tempo de Rua')),
                ('usuario', models.BooleanField(default=False, verbose_name='Usuario Quimico')),
            ],
            options={
                'verbose_name': 'Família',
                'verbose_name_plural': 'Famílias',
            },
        ),
    ]
