# Generated by Django 4.0.4 on 2022-04-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_familia_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
